version: '3.8'

services:
    kusonime-api:
        container_name: app
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile.prod
        image: kusonime-api:latest
        restart: always
        ports:
            - 8000:8000
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
